# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('city_longitude', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(max_length=200)),
                ('flight_carrier', models.CharField(max_length=200)),
                ('flight_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=200)),
                ('hotel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_planner_app.Trip'),
        ),
    ]
