# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
